DROP TABLE restaurants IF EXISTS CASCADE;
DROP TABLE users IF EXISTS CASCADE;
DROP TABLE user_roles IF EXISTS CASCADE;
DROP TABLE dishes IF EXISTS CASCADE;

DROP SEQUENCE global_seq IF EXISTS ;

CREATE SEQUENCE global_seq AS INTEGER START WITH 100000;

CREATE TABLE restaurants (
  id          INTEGER GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
  name        VARCHAR(255)   NOT NULL,
  votes       INTEGER
);

CREATE TABLE users
(
  id                INTEGER GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
  name              VARCHAR(255)                 NOT NULL,
  email             VARCHAR(255)                 NOT NULL,
  password          VARCHAR(255)                 NOT NULL,
  restaurantVotedId INTEGER,
  FOREIGN KEY (restaurantVotedId) REFERENCES restaurants (id) ON DELETE CASCADE
);

CREATE TABLE user_roles
(
  user_id INTEGER NOT NULL,
  role    VARCHAR(255),
  CONSTRAINT user_roles_idx UNIQUE (user_id, role),
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE dishes (
  id            INTEGER GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
  name          VARCHAR(255)    NOT NULL,
  price         INTEGER         NOT NULL,
  restaurantId  INTEGER,
  FOREIGN KEY (restaurantId) REFERENCES restaurants (id) ON DELETE CASCADE
);